// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: convo.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Participants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *Participants) Reset() {
	*x = Participants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Participants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participants) ProtoMessage() {}

func (x *Participants) ProtoReflect() protoreflect.Message {
	mi := &file_convo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participants.ProtoReflect.Descriptor instead.
func (*Participants) Descriptor() ([]byte, []int) {
	return file_convo_proto_rawDescGZIP(), []int{0}
}

func (x *Participants) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Convo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Participants *Participants `protobuf:"bytes,2,opt,name=participants,proto3" json:"participants,omitempty"`
	CreatedAt    uint64        `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Convo) Reset() {
	*x = Convo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Convo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Convo) ProtoMessage() {}

func (x *Convo) ProtoReflect() protoreflect.Message {
	mi := &file_convo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Convo.ProtoReflect.Descriptor instead.
func (*Convo) Descriptor() ([]byte, []int) {
	return file_convo_proto_rawDescGZIP(), []int{1}
}

func (x *Convo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Convo) GetParticipants() *Participants {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Convo) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ConvoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Convos []*Convo `protobuf:"bytes,1,rep,name=convos,proto3" json:"convos,omitempty"`
}

func (x *ConvoList) Reset() {
	*x = ConvoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvoList) ProtoMessage() {}

func (x *ConvoList) ProtoReflect() protoreflect.Message {
	mi := &file_convo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvoList.ProtoReflect.Descriptor instead.
func (*ConvoList) Descriptor() ([]byte, []int) {
	return file_convo_proto_rawDescGZIP(), []int{2}
}

func (x *ConvoList) GetConvos() []*Convo {
	if x != nil {
		return x.Convos
	}
	return nil
}

type NewConvoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Participants *Participants `protobuf:"bytes,1,opt,name=participants,proto3" json:"participants,omitempty"`
}

func (x *NewConvoReq) Reset() {
	*x = NewConvoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewConvoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConvoReq) ProtoMessage() {}

func (x *NewConvoReq) ProtoReflect() protoreflect.Message {
	mi := &file_convo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConvoReq.ProtoReflect.Descriptor instead.
func (*NewConvoReq) Descriptor() ([]byte, []int) {
	return file_convo_proto_rawDescGZIP(), []int{3}
}

func (x *NewConvoReq) GetParticipants() *Participants {
	if x != nil {
		return x.Participants
	}
	return nil
}

type ListConvoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ListConvoReq) Reset() {
	*x = ListConvoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConvoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConvoReq) ProtoMessage() {}

func (x *ListConvoReq) ProtoReflect() protoreflect.Message {
	mi := &file_convo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConvoReq.ProtoReflect.Descriptor instead.
func (*ListConvoReq) Descriptor() ([]byte, []int) {
	return file_convo_proto_rawDescGZIP(), []int{4}
}

func (x *ListConvoReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_convo_proto protoreflect.FileDescriptor

var file_convo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74,
	0x32, 0x74, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f,
	0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x1f,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x74, 0x32, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x6c, 0x0a, 0x05, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x32, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2f, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x76, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x32, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x73, 0x22, 0x44,
	0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a,
	0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x32, 0x61, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e,
	0x74, 0x32, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x0a, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x12, 0x29, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x76, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x72, 0x69, 0x33, 0x31, 0x32, 0x30, 0x30, 0x36, 0x2f,
	0x74, 0x65, 0x72, 0x6d, 0x32, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_convo_proto_rawDescOnce sync.Once
	file_convo_proto_rawDescData = file_convo_proto_rawDesc
)

func file_convo_proto_rawDescGZIP() []byte {
	file_convo_proto_rawDescOnce.Do(func() {
		file_convo_proto_rawDescData = protoimpl.X.CompressGZIP(file_convo_proto_rawDescData)
	})
	return file_convo_proto_rawDescData
}

var file_convo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_convo_proto_goTypes = []interface{}{
	(*Participants)(nil), // 0: t2t.Participants
	(*Convo)(nil),        // 1: t2t.Convo
	(*ConvoList)(nil),    // 2: t2t.ConvoList
	(*NewConvoReq)(nil),  // 3: t2t.NewConvoReq
	(*ListConvoReq)(nil), // 4: t2t.ListConvoReq
	(*User)(nil),         // 5: t2t.User
}
var file_convo_proto_depIdxs = []int32{
	5, // 0: t2t.Participants.users:type_name -> t2t.User
	0, // 1: t2t.Convo.participants:type_name -> t2t.Participants
	1, // 2: t2t.ConvoList.convos:type_name -> t2t.Convo
	0, // 3: t2t.NewConvoReq.participants:type_name -> t2t.Participants
	5, // 4: t2t.ListConvoReq.user:type_name -> t2t.User
	3, // 5: t2t.ConvoService.Create:input_type -> t2t.NewConvoReq
	4, // 6: t2t.ConvoService.List:input_type -> t2t.ListConvoReq
	1, // 7: t2t.ConvoService.Create:output_type -> t2t.Convo
	2, // 8: t2t.ConvoService.List:output_type -> t2t.ConvoList
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_convo_proto_init() }
func file_convo_proto_init() {
	if File_convo_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_convo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Participants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Convo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewConvoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConvoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_convo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_convo_proto_goTypes,
		DependencyIndexes: file_convo_proto_depIdxs,
		MessageInfos:      file_convo_proto_msgTypes,
	}.Build()
	File_convo_proto = out.File
	file_convo_proto_rawDesc = nil
	file_convo_proto_goTypes = nil
	file_convo_proto_depIdxs = nil
}
