// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: msg.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgFetchKindBy int32

const (
	MsgFetchKindBy_Id       MsgFetchKindBy = 0
	MsgFetchKindBy_Unread   MsgFetchKindBy = 1
	MsgFetchKindBy_ConvoId  MsgFetchKindBy = 2
	MsgFetchKindBy_AuthorId MsgFetchKindBy = 3
)

// Enum value maps for MsgFetchKindBy.
var (
	MsgFetchKindBy_name = map[int32]string{
		0: "Id",
		1: "Unread",
		2: "ConvoId",
		3: "AuthorId",
	}
	MsgFetchKindBy_value = map[string]int32{
		"Id":       0,
		"Unread":   1,
		"ConvoId":  2,
		"AuthorId": 3,
	}
)

func (x MsgFetchKindBy) Enum() *MsgFetchKindBy {
	p := new(MsgFetchKindBy)
	*p = x
	return p
}

func (x MsgFetchKindBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgFetchKindBy) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (MsgFetchKindBy) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x MsgFetchKindBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgFetchKindBy.Descriptor instead.
func (MsgFetchKindBy) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Convo     *Convo `protobuf:"bytes,2,opt,name=convo,proto3" json:"convo,omitempty"`
	Author    *User  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Recipient *User  `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Body      string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	UnixTime  int64  `protobuf:"varint,6,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	IsRead    bool   `protobuf:"varint,7,opt,name=isRead,proto3" json:"isRead,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Msg) GetConvo() *Convo {
	if x != nil {
		return x.Convo
	}
	return nil
}

func (x *Msg) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Msg) GetRecipient() *User {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *Msg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Msg) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Msg) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type MsgList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Msg `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MsgList) Reset() {
	*x = MsgList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgList) ProtoMessage() {}

func (x *MsgList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgList.ProtoReflect.Descriptor instead.
func (*MsgList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MsgList) GetMessages() []*Msg {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MsgSendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MsgSendRes) Reset() {
	*x = MsgSendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendRes) ProtoMessage() {}

func (x *MsgSendRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendRes.ProtoReflect.Descriptor instead.
func (*MsgSendRes) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSendRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MsgFetchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     MsgFetchKindBy `protobuf:"varint,1,opt,name=kind,proto3,enum=t2t.MsgFetchKindBy" json:"kind,omitempty"`
	Id       string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Unread   bool           `protobuf:"varint,3,opt,name=unread,proto3" json:"unread,omitempty"`
	ConvoId  string         `protobuf:"bytes,4,opt,name=convoId,proto3" json:"convoId,omitempty"`
	AuthorId string         `protobuf:"bytes,5,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *MsgFetchReq) Reset() {
	*x = MsgFetchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFetchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFetchReq) ProtoMessage() {}

func (x *MsgFetchReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFetchReq.ProtoReflect.Descriptor instead.
func (*MsgFetchReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MsgFetchReq) GetKind() MsgFetchKindBy {
	if x != nil {
		return x.Kind
	}
	return MsgFetchKindBy_Id
}

func (x *MsgFetchReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgFetchReq) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

func (x *MsgFetchReq) GetConvoId() string {
	if x != nil {
		return x.ConvoId
	}
	return ""
}

func (x *MsgFetchReq) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x32, 0x74,
	0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x6f,
	0x6e, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x52, 0x05, 0x63, 0x6f,
	0x6e, 0x76, 0x6f, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x22, 0x2f, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0a, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x94, 0x01, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x12, 0x27, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4b, 0x69,
	0x6e, 0x64, 0x42, 0x79, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x2a, 0x3f, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x49, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x10, 0x03, 0x32, 0x59, 0x0a, 0x0a, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x08, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0f, 0x2e, 0x74, 0x32, 0x74, 0x2e,
	0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x10, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x72, 0x69, 0x33, 0x31, 0x32, 0x30, 0x30, 0x36, 0x2f, 0x74, 0x65,
	0x72, 0x6d, 0x32, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_proto_goTypes = []interface{}{
	(MsgFetchKindBy)(0), // 0: t2t.MsgFetchKindBy
	(*Msg)(nil),         // 1: t2t.Msg
	(*MsgList)(nil),     // 2: t2t.MsgList
	(*MsgSendRes)(nil),  // 3: t2t.MsgSendRes
	(*MsgFetchReq)(nil), // 4: t2t.MsgFetchReq
	(*Convo)(nil),       // 5: t2t.Convo
	(*User)(nil),        // 6: t2t.User
}
var file_msg_proto_depIdxs = []int32{
	5, // 0: t2t.Msg.convo:type_name -> t2t.Convo
	6, // 1: t2t.Msg.author:type_name -> t2t.User
	6, // 2: t2t.Msg.recipient:type_name -> t2t.User
	1, // 3: t2t.MsgList.messages:type_name -> t2t.Msg
	0, // 4: t2t.MsgFetchReq.kind:type_name -> t2t.MsgFetchKindBy
	1, // 5: t2t.MsgService.Send:input_type -> t2t.Msg
	4, // 6: t2t.MsgService.Search:input_type -> t2t.MsgFetchReq
	3, // 7: t2t.MsgService.Send:output_type -> t2t.MsgSendRes
	2, // 8: t2t.MsgService.Search:output_type -> t2t.MsgList
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	file_user_proto_init()
	file_convo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFetchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
