// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: msg.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSearchKindBy int32

const (
	MsgSearchKindBy_Id       MsgSearchKindBy = 0
	MsgSearchKindBy_Unread   MsgSearchKindBy = 1
	MsgSearchKindBy_ConvoId  MsgSearchKindBy = 2
	MsgSearchKindBy_AuthorId MsgSearchKindBy = 3
)

// Enum value maps for MsgSearchKindBy.
var (
	MsgSearchKindBy_name = map[int32]string{
		0: "Id",
		1: "Unread",
		2: "ConvoId",
		3: "AuthorId",
	}
	MsgSearchKindBy_value = map[string]int32{
		"Id":       0,
		"Unread":   1,
		"ConvoId":  2,
		"AuthorId": 3,
	}
)

func (x MsgSearchKindBy) Enum() *MsgSearchKindBy {
	p := new(MsgSearchKindBy)
	*p = x
	return p
}

func (x MsgSearchKindBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgSearchKindBy) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (MsgSearchKindBy) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x MsgSearchKindBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgSearchKindBy.Descriptor instead.
func (MsgSearchKindBy) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Convo     *Convo `protobuf:"bytes,2,opt,name=convo,proto3" json:"convo,omitempty"`
	Author    *User  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Recipient *User  `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Body      string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	UnixTime  uint64 `protobuf:"varint,6,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	IsRead    bool   `protobuf:"varint,7,opt,name=isRead,proto3" json:"isRead,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Msg) GetConvo() *Convo {
	if x != nil {
		return x.Convo
	}
	return nil
}

func (x *Msg) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Msg) GetRecipient() *User {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *Msg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Msg) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Msg) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type MsgList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Msg `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MsgList) Reset() {
	*x = MsgList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgList) ProtoMessage() {}

func (x *MsgList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgList.ProtoReflect.Descriptor instead.
func (*MsgList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MsgList) GetMessages() []*Msg {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MsgSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Convo    *Convo `protobuf:"bytes,1,opt,name=convo,proto3" json:"convo,omitempty"`
	Author   *User  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Body     string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	UnixTime uint64 `protobuf:"varint,4,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
}

func (x *MsgSendReq) Reset() {
	*x = MsgSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendReq) ProtoMessage() {}

func (x *MsgSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendReq.ProtoReflect.Descriptor instead.
func (*MsgSendReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSendReq) GetConvo() *Convo {
	if x != nil {
		return x.Convo
	}
	return nil
}

func (x *MsgSendReq) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *MsgSendReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MsgSendReq) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type MsgSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    MsgSearchKindBy `protobuf:"varint,1,opt,name=kind,proto3,enum=t2t.MsgSearchKindBy" json:"kind,omitempty"`
	Id      string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Unread  bool            `protobuf:"varint,3,opt,name=unread,proto3" json:"unread,omitempty"`
	ConvoId string          `protobuf:"bytes,4,opt,name=convoId,proto3" json:"convoId,omitempty"`
	UserId  string          `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MsgSearchReq) Reset() {
	*x = MsgSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSearchReq) ProtoMessage() {}

func (x *MsgSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSearchReq.ProtoReflect.Descriptor instead.
func (*MsgSearchReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MsgSearchReq) GetKind() MsgSearchKindBy {
	if x != nil {
		return x.Kind
	}
	return MsgSearchKindBy_Id
}

func (x *MsgSearchReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgSearchReq) GetUnread() bool {
	if x != nil {
		return x.Unread
	}
	return false
}

func (x *MsgSearchReq) GetConvoId() string {
	if x != nil {
		return x.ConvoId
	}
	return ""
}

func (x *MsgSearchReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x32, 0x74,
	0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x6f,
	0x6e, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x52, 0x05, 0x63, 0x6f,
	0x6e, 0x76, 0x6f, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x22, 0x2f, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x76,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x43, 0x6f,
	0x6e, 0x76, 0x6f, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x32, 0x74,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x92,
	0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x28, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x2a, 0x40, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4b, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x76, 0x6f, 0x49, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x10, 0x03, 0x32, 0x5a, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0f, 0x2e, 0x74, 0x32,
	0x74, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x08, 0x2e, 0x74,
	0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x11, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x74, 0x32, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x75, 0x72, 0x69, 0x33, 0x31, 0x32, 0x30, 0x30, 0x36, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x32,
	0x74, 0x65, 0x72, 0x6d, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_proto_goTypes = []interface{}{
	(MsgSearchKindBy)(0), // 0: t2t.MsgSearchKindBy
	(*Msg)(nil),          // 1: t2t.Msg
	(*MsgList)(nil),      // 2: t2t.MsgList
	(*MsgSendReq)(nil),   // 3: t2t.MsgSendReq
	(*MsgSearchReq)(nil), // 4: t2t.MsgSearchReq
	(*Convo)(nil),        // 5: t2t.Convo
	(*User)(nil),         // 6: t2t.User
}
var file_msg_proto_depIdxs = []int32{
	5, // 0: t2t.Msg.convo:type_name -> t2t.Convo
	6, // 1: t2t.Msg.author:type_name -> t2t.User
	6, // 2: t2t.Msg.recipient:type_name -> t2t.User
	1, // 3: t2t.MsgList.messages:type_name -> t2t.Msg
	5, // 4: t2t.MsgSendReq.convo:type_name -> t2t.Convo
	6, // 5: t2t.MsgSendReq.author:type_name -> t2t.User
	0, // 6: t2t.MsgSearchReq.kind:type_name -> t2t.MsgSearchKindBy
	3, // 7: t2t.MsgService.Send:input_type -> t2t.MsgSendReq
	4, // 8: t2t.MsgService.Search:input_type -> t2t.MsgSearchReq
	1, // 9: t2t.MsgService.Send:output_type -> t2t.Msg
	2, // 10: t2t.MsgService.Search:output_type -> t2t.MsgList
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	file_user_proto_init()
	file_convo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
