[keybindings.Editing]
"Esc" = { Mode = "Normal" }
"Enter" = "Enter"
"<Ctrl-c>" = "Quit"
[keybindings.Normal]
"q" = "Quit"
"<Ctrl-d>" = "Quit"
"<Ctrl-c>" = "Quit"
"<Ctrl-z>" = "Suspend"
"Enter" = "Enter"
"i" = { Mode = "Editing" }
