# fly.toml app configuration file generated for t2tserver-aged-forest-4041 on 2024-05-09T11:14:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 't2tserver'
primary_region = 'lax'

[build]

[[services]]
internal_port = 54321
protocol = "tcp"

[[services.ports]]
handlers = ["tls"]
port = "443"

[services.ports.tls_options]
alpn = ["h2"]

# [http_service]
# internal_port = 8080
# force_https = true
# auto_stop_machines = true
# auto_start_machines = true
# min_machines_running = 0
# processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
