name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and install protoc
      run: |
        sudo apt install -y protobuf-compiler
        protoc --version
        rustup target add x86_64-pc-windows-gnu
        sudo apt-get install gcc-mingw-w64

    - name: Build windows
      run: cd rs && cargo build --target x86_64-pc-windows-gnu --release 

    - name: Build Linux
      run: cd rs && cargo build --release 

    # - name: Run tests
    #   run: cd rs && cargo test --verbose
    # - name: ls dirs
    #   run: cd rs/target/x86_64-pc-windows-gnu/release && ls -la

    - name: Push artifact to releases
      uses: actions/upload-artifact@v4
      with:
        name: t2t
        path: |
          rs/target/release/t2t
          rs/target/x86_64-pc-windows-gnu/release/t2t.exe
